package event

const (
	API               = "API"
	CALL_UPDATE       = "CALL_UPDATE"
	CALL_SECURE       = "CALL_SECURE"
	DEL_SCHEDULE      = "DEL_SCHEDULE"
	ADD_SCHEDULE      = "ADD_SCHEDULE"
	HEARTBEAT         = "HEARTBEAT"
	RE_SCHEDULE       = "RE_SCHEDULE"
	PRESENCE_PROBE    = "PRESENCE_PROBE"
	PRESENCE_IN       = "PRESENCE_IN"
	RECV_RTCP_MESSAGE = "RECV_RTCP_MESSAGE"
	MESSAGE_QUERY     = "MESSAGE_QUERY"
	MESSAGE_WAITING   = "MESSAGE_WAITING"
	PRIVATE_COMMAND   = "PRIVATE_COMMAND"
	SESSION_HEARTBEAT = "SESSION_HEARTBEAT"
	BACKGROUND_JOB    = "BACKGROUND_JOB"
	CUSTOM            = "CUSTOM"
	DTMF              = "DTMF"
	// 通道创建
	CHANNEL_CREATE = "CHANNEL_CREATE"

	CHANNEL_PARK   = "CHANNEL_PARK"
	CHANNEL_UNPARK = "CHANNEL_UNPARK"
	// 接通通话
	CHANNEL_ANSWER = "CHANNEL_ANSWER"
	// 接通通话
	DETECTED_SPEECH = "DETECTED_SPEECH"
	// 桥接通道
	CHANNEL_BRIDGE = "CHANNEL_BRIDGE"
	// 通道断开桥接
	CHANNEL_UNBRIDGE = "CHANNEL_UNBRIDGE"
	// 通道状态
	CHANNEL_STATE = "CHANNEL_STATE"
	// 通道呼叫状态
	CHANNEL_CALLSTATE = "CHANNEL_CALLSTATE"
	// 通道执行app
	CHANNEL_EXECUTE = "CHANNEL_EXECUTE"
	// 通道执行app 执行完成
	CHANNEL_EXECUTE_COMPLETE = "CHANNEL_EXECUTE_COMPLETE"
	// 通道挂机
	CHANNEL_HANGUP = "CHANNEL_HANGUP"
	// 通道挂机完成
	CHANNEL_HANGUP_COMPLETE = "CHANNEL_HANGUP_COMPLETE"

	CHANNEL_OUTGOING = "CHANNEL_OUTGOING"
	// 通道销毁
	CHANNEL_DESTROY = "CHANNEL_DESTROY"

	// 播放开始
	PLAYBACK_START = "PLAYBACK_START"
	// 播放结束
	PLAYBACK_STOP = "PLAYBACK_STOP"
)
